const data = {
  products: [
    {
      _id: 1,
      name: "Veef Burger",
      category: "Comfort",
      image: "/images/1.png",
      price: 7.99,
      stockCount: 81,
      brand: "Beyond",
      rating: 4.6,
      numReviews: 1243,
    },
    {
      _id: 2,
      name: "Green Carbonara",
      category: "Comfort",
      image: "/images/2.png",
      price: 11.99,
      stockCount: 8,
      brand: "Beyond",
      rating: 4.3,
      numReviews: 1039,
    },
    {
      _id: 3,
      name: "Japanesse Okra Curry",
      category: "Asian",
      image: "/images/3.png",
      price: 15.49,
      stockCount: 1,
      brand: "Yeung Man Cooking",
      rating: 4.8,
      numReviews: 243,
    },
    {
      _id: 4,
      name: "Tofu Pad Thai",
      category: "Asian",
      image: "/images/4.png",
      price: 12.99,
      stockCount: 0,
      brand: "Young Man Cooking",
      rating: 4.9,
      numReviews: 86,
    },
    {
      _id: 5,
      name: "Green Fried Chicken",
      category: "Soul Food",
      image: "/images/5.png",
      price: 7.99,
      stockCount: 3,
      brand: "BT",
      rating: 4.1,
      numReviews: 33,
    },
    {
      _id: 6,
      name: "Green Soul Bowl",
      category: "Soul Food",
      image: "/images/6.png",
      price: 15.49,
      stockCount: 5,
      brand: "BT",
      rating: 4.3,
      numReviews: 115,
    },
  ],
};

export default data;
